"""First migration

Revision ID: 318399a6cded
Revises: 
Create Date: 2020-05-29 12:37:48.295630

"""
from alembic import op
import sqlalchemy as sa
import matchflix


# revision identifiers, used by Alembic.
revision = '318399a6cded'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release',
    sa.Column('id', matchflix.db.base_class.GUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('cover', sa.String(), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_release_description'), 'release', ['description'], unique=False)
    op.create_index(op.f('ix_release_id'), 'release', ['id'], unique=False)
    op.create_index(op.f('ix_release_title'), 'release', ['title'], unique=False)
    op.create_table('user',
    sa.Column('id', matchflix.db.base_class.GUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('answer',
    sa.Column('id', matchflix.db.base_class.GUID(), nullable=False),
    sa.Column('action', sa.Enum('LEFT', 'RIGHT', 'DID_NOT_WATCH', name='actionenum'), nullable=True),
    sa.Column('owner_id', matchflix.db.base_class.GUID(), nullable=True),
    sa.Column('release_id', matchflix.db.base_class.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['release_id'], ['release.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_id'), 'answer', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_id'), table_name='answer')
    op.drop_table('answer')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_release_title'), table_name='release')
    op.drop_index(op.f('ix_release_id'), table_name='release')
    op.drop_index(op.f('ix_release_description'), table_name='release')
    op.drop_table('release')
    # ### end Alembic commands ###
