"""First migration

Revision ID: e2297dc729e2
Revises:
Create Date: 2020-05-27 04:06:47.964990

"""
import sqlalchemy as sa
from alembic import op

import matchflix

# revision identifiers, used by Alembic.
revision = "e2297dc729e2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "release",
        sa.Column("id", matchflix.db.base_class.GUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("cover", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_release_description"), "release", ["description"], unique=False
    )
    op.create_index(op.f("ix_release_id"), "release", ["id"], unique=False)
    op.create_index(op.f("ix_release_title"), "release", ["title"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", matchflix.db.base_class.GUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_table(
        "answer",
        sa.Column("id", matchflix.db.base_class.GUID(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("LEFT", "RIGHT", "DID_NOT_WATCH", name="actionenum"),
            nullable=True,
        ),
        sa.Column("owner_id", matchflix.db.base_class.GUID(), nullable=True),
        sa.Column("release_id", matchflix.db.base_class.GUID(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"],),
        sa.ForeignKeyConstraint(["release_id"], ["release.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_answer_id"), "answer", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_answer_id"), table_name="answer")
    op.drop_table("answer")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_release_title"), table_name="release")
    op.drop_index(op.f("ix_release_id"), table_name="release")
    op.drop_index(op.f("ix_release_description"), table_name="release")
    op.drop_table("release")
    # ### end Alembic commands ###
